
data_base: 'datasets'
map_config: rnd_obstacle_v2
run_name: random_run_name
ep: 0
seed: 88



dataset_for_aug: final_dataset-test_0.05/train
new_dataset_name: dataset-with-vel-map
which_test: unseen_map
save_dir: video
num_unseen_map: 47
test_percentage: 0.05
run_mode: hil
sim_mode: eval
data_aug: False
map_config: 'rnd_obstacle_v2'
run_name: 'success_1'
trained_model: ''
ep: 0
save_img: True
control_type: 'continuous'
traj_dir: ''
dp_mode: 'demo'
keyboard_actions: False